### ISSUE TITLE
AzListView 看起来非常炫酷，是不是必须一次性加载完Data才可以使用呢？

### ISSUE THREAD

**Issue by twovs** [flutterchina/azlistview#1]
对于滚动持续加载数据的listview是否不适用呢？

个人猜想因为涉及到排序问题，所以插件应该只适用于一次性加载完成数据后的数据，也就是说列表大小应该是一次性加载完成的吧？

期待你的答复

**Comment by Sky24n** [comment]
应该是适用的，把全部数据再排序一次序。

**Comment by twovs** [comment]
谢谢你的答复，我再尝试尝试
