### ISSUE TITLE
你好。我按照您提供的城市列表案例运行，但把数据量改大了一些，约有2500条左右，点击右侧的字母导航，会出现严重的延迟现象。请问，针对大量数据时应该如何处理以避免延迟？

### ISSUE THREAD

**Issue by conggege325** [flutterchina/azlistview#12]

**Comment by Sky24n** [comment]
是debug还release，debug模式啥都卡

**Comment by xypeng12345** [comment]
@Sky24n  你好，release也卡

**Comment by sweatfryash** [comment]
你好，我大概有900条数据就很卡了，感觉这个列表的性能是和数据量直接相关的，不知道是实现方法的原因还是flutter的本身性能的原因啊。大家有解决方案的话可以分享一哈呗

**Comment by limocute** [comment]
同问，我这边release下600-700就很卡了

**Comment by wudijimao** [comment]
我们这边正在着手解决这个问题，比较好处理回头可以提pull_request过来

**Comment by wudijimao** [comment]
经排查和修改代码：https://github.com/YoudaoMobile/azlistview/tree/master
将Hit重建时避免了整体刷新，整体效率还是很低，经查资料得出是Flutter原生的 ListView的问题，jump距离越远越卡，后续解决方案未定，会持续跟踪

**Comment by jiangyh1024** [comment]
请问这个问题如何能解决呢 lazy loading 不行么

**Comment by xhowe** [comment]
目前源码的实现是一组数据的ListView放在一个Stack的children里，这样ListView.builder是否能起到原本的builder作用？

**Comment by Sky24n** [comment]
fix，请使用v1.0.0版本
