### ISSUE TITLE
当语音支持国际化(左右排版) 就会出现 排版错误

### ISSUE THREAD

**Issue by liuchuancong** [flutterchina/azlistview#15]
tag 始终在左边  右边的字母排序 始终在右边

**Comment by Sky24n** [comment]
把图发上来看看呢

**Comment by liuchuancong** [comment]
https://github.com/flutterchina/azlistview/blob/b8a1a0cb3f74df4a75da2c0e2bf8b1187a23672d/lib/src/az_listview.dart#L198

**Comment by Sky24n** [comment]
你的意思是想把字母位置开放出来？

**Comment by liuchuancong** [comment]
是的，国际化之后  我的是阿语  应该在左边显示 但是  在您源码那里没有选项 导致始终在左边  我不得不克隆代码本地修改

**Comment by liuchuancong** [comment]
如果支持搜索过滤 将更完美 https://github.com/AppleEducate/plugins
