### ISSUE TITLE
您好 在里面加分割线如何保证最后一个不加呢?

### ISSUE THREAD

**Issue by lihaotian0607** [flutterchina/azlistview#16]
现在加了 `Divider(height: 0.1, indent: 68)`

但是如果 A 这个Tag下只有一个数据或者最后一个数据的时候不想让分割线显示 但是好像没办法 请问有什么好办法呢?

**Comment by wpajqz** [comment]
通过是否显示tag来判断，tag的上一个不显示下划线
`  Widget _buildListItem(BuildContext context, int index) {
    final model = widget.data[index];
    bool lastSegment = false;

    if (index + 1 < widget.data.length) {
      lastSegment = widget.data[index + 1].isShowSuspension;
    } else {
      lastSegment = true;
    }

    return Column(
      children: [
        Offstage(
          offstage: model.isShowSuspension != true,
          child: _buildSusWidget(model.getSuspensionTag()),
        ),
        Container(
          height: _itemHeight.toDouble(),
          child: widget.itemBuilder(context, model, lastSegment),
        ),
      ],
    );
  }`

**Comment by Sky24n** [comment]
fix，请使用v1.0.0版本
