### ISSUE TITLE
indexBarBuilder 高度超限

### ISSUE THREAD

**Issue by LNyears** [flutterchina/azlistview#19]
你好，当我使用本插件时，当我顶部有搜索输入，弹出键盘时indexBarBuilder的高度会超限：
azlistview: ^0.1.2
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤

**Comment by Sky24n** [comment]
Scaffold 
resizeToAvoidBottomPadding:false
