### ISSUE TITLE
选择index后,会出现popup不隐藏

### ISSUE THREAD

**Issue by yikwing** [flutterchina/azlistview#2]
![Kapture 2019-03-20 at 12 15 44](https://user-images.githubusercontent.com/20245290/54658832-59ceec00-4b0a-11e9-8d23-a24ed2e553b0.gif)

复制example的demo也是一样的效果,点击选择后不隐藏,但是滑动选择会隐藏

**Comment by Sky24n** [comment]
我这边试了demo，都是正常的啊

**Comment by yikwing** [comment]
demo确实是正常的  但是我这边不知道什么问题, 就算把demo的拷过去也是不隐藏.https://github.com/yikwing/flutter_wechat/blob/master/lib/home_contacts.dart

**Comment by Sky24n** [comment]
用最新版0.1.1
