### ISSUE TITLE
IndexBar在Andrid横屏时越界

### ISSUE THREAD

**Issue by zhaoxinming** [flutterchina/azlistview#25]
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 25 pixels on the bottom.

The relevant error-causing widget was: 
  Column file:///Users/zhaoxm/workspace/flutter/azlistview/lib/src/index_bar.dart:244:18
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#4ae29 relayoutBoundary=up9 OVERFLOWING
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=36.0, 0.0<=h<=342.7)
...  size: Size(36.0, 342.7)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: min
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by zhaoxinming** [comment]
Demo 直接运行后横屏即课复现问题现象

**Comment by Sky24n** [comment]
横屏的高度小于IndexBar高度，肯定会溢出！这有什么问题嘛

**Comment by zhaoxinming** [comment]
不需要适配横屏情况吗？

**Comment by Sky24n** [comment]
你觉得应该怎么适配呢？或者有没有类似的app可以提供下

**Comment by zhaoxinming** [comment]
我个人感觉是不是可以在屏幕高度不够的时候加一个滚动，或者可以传入indexbar的高度留给使用方去设置，这样不会导致超过高度部分看不见也不能操作，个人看法

**Comment by Sky24n** [comment]
1、加滚动，那按下Indexbar拖动事件咋办？
2、你可以自定义个Indexbar啊

**Comment by zhaoxinming** [comment]
嗯 ，好的

**Comment by zhaoxinming** [comment]
找到了一种解决方案，不知道可不可行，可以加一个FittedBox 在indexBar的外面 ，这样就会自动缩放indexBar，而且不影响拖动事件了。
child: SizedBox(
        child: FittedBox(
          fit: BoxFit.contain,
          child: new Column(
            mainAxisSize: MainAxisSize.min,
            children: children,
          ),
        ),
      ),

**Comment by leeyisoft** [comment]
> 横屏的高度小于IndexBar高度，肯定会溢出！这有什么问题嘛

这个没有什么不就措施吗？求解决方法
