### ISSUE TITLE
当页面有键盘弹出时，indexbar UI溢出

### ISSUE THREAD

**Issue by zzpmaster** [flutterchina/azlistview#3]
当页面有textfield时，indexbar bottom溢出。 

[截图地址](https://fishing-1256813529.cos.ap-beijing.myqcloud.com/bottom_overflowed.png
)

![image](https://fishing-1256813529.cos.ap-beijing.myqcloud.com/bottom_overflowed.png)

**Comment by Sky24n** [comment]
Scaffold  resizeToAvoidBottomPadding:false


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by zzpmaster** [comment]
@Sky24n thank you.
