### ISSUE TITLE
Load image

### ISSUE THREAD

**Issue by odejinmi** [flutterchina/azlistview#32]
I was unable to load an image on the list, I use both assets and network image still the same thing, is there I have to do this

**Comment by Sky24n** [comment]
Please provide relevant code.

**Comment by odejinmi** [comment]
import 'dart:convert';

import 'package:azlistview/azlistview.dart';
import 'package:flutter/material.dart';

class CityModel extends ISuspensionBean {
  String name;
  String tagIndex;
  String namePinyin;

  CityModel({
    this.name,
    this.tagIndex,
    this.namePinyin,
  });

  CityModel.fromJson(Map<String, dynamic> json) : name = json['name'];

  Map<String, dynamic> toJson() => {
    'name': name,
//        'tagIndex': tagIndex,
//        'namePinyin': namePinyin,
//        'isShowSuspension': isShowSuspension
  };

  @override
  String getSuspensionTag() => tagIndex;

  @override
  String toString() => json.encode(this);
}

class ContactInfo extends ISuspensionBean {
  String name;
  String tagIndex;
  String namePinyin;

  Color bgColor;
  IconData iconData;

  String img;
  String id;
  String firstletter;

  ContactInfo({
    this.name,
    this.tagIndex,
    this.namePinyin,
    this.bgColor,
    this.iconData,
    this.img,
    this.id,
    this.firstletter,
  });

  ContactInfo.fromJson(Map<String, dynamic> json)
      : name = json['name']+" "+json['number'],
        img = json['img'],
        id = json['id']?.toString(),
        firstletter = json['firstletter'];

  Map<String, dynamic> toJson() => {
//        'id': id,
    'name': name,
    'img': img,
//        'firstletter': firstletter,
//        'tagIndex': tagIndex,
//        'namePinyin': namePinyin,
//        'isShowSuspension': isShowSuspension
  };

  @override
  String getSuspensionTag() => tagIndex;

  @override
  String toString() => json.encode(this);
}

**Comment by odejinmi** [comment]
I am loading the image from json file

**Comment by odejinmi** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_app/Screens/common/index.dart';

class Utils {
  static String getImgPath(String name, {String format: 'png'}) {
    return 'assets/images/$name.$format';
  }

  static void showSnackBar(BuildContext context, String msg) {
    print(msg);
    Scaffold.of(context).showSnackBar(
      SnackBar(
        content: Text(msg),
        duration: Duration(seconds: 2),
      ),
    );
  }

  static Widget getSusItem(BuildContext context, String tag,
      {double susHeight = 40}) {
    if (tag == '★') {
      tag = '★ 热门城市';
    }
    return Container(
      height: susHeight,
      width: MediaQuery.of(context).size.width,
      padding: EdgeInsets.only(left: 16.0),
      color: Color(0xFFF3F4F5),
      alignment: Alignment.centerLeft,
      child: Text(
        '$tag',
        softWrap: false,
        style: TextStyle(
          fontSize: 14.0,
          color: Color(0xFF666666),
        ),
      ),
    );
  }

  static Widget getListItem(BuildContext context, CityModel model,
      {double susHeight = 40}) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Offstage(
          offstage: !(model.isShowSuspension == true),
          child: getSusItem(context, model.getSuspensionTag(),
              susHeight: susHeight),
        ),
        ListTile(
          title: Text(model.name),
          onTap: () {
            //LogUtil.e("onItemClick : $model");
            Utils.showSnackBar(context, 'onItemClick : ${model.name}');
          },
        )
      ],
    );
  }

  static Widget getWeChatListItem(
      BuildContext context,
      ContactInfo model, {
        double susHeight = 40,
        Color defHeaderBgColor,
      }) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Offstage(
          offstage: !(model.isShowSuspension == true),
          child: getSusItem(context, model.getSuspensionTag(),
              susHeight: susHeight),
        ),
        getWeChatItem(context, model, defHeaderBgColor: defHeaderBgColor),
      ],
    );
  }

  static Widget getWeChatItem(
      BuildContext context,
      ContactInfo model, {
        Color defHeaderBgColor,
      }) {
    DecorationImage image;
//    if (model.img != null && model.img.isNotEmpty) {
//      image = DecorationImage(
//        image: CachedNetworkImageProvider(model.img),
//        fit: BoxFit.contain,
//      );
//    }
    return ListTile(
      leading: Container(
        width: 36,
        height: 36,
        decoration: BoxDecoration(
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(4.0),
          color: model.bgColor ?? defHeaderBgColor,
          image: image,
        ),
        child: model.iconData == null
            ? null
            : Icon(
          model.iconData,
          color: Colors.white,
          size: 20,
        ),
      ),
      title: Text(model.name),
      onTap: () {
        //LogUtil.e("onItemClick : $model");
        Utils.showSnackBar(context, 'onItemClick : ${model.name}');
      },
    );
  }
}

**Comment by odejinmi** [comment]
`
import 'package:azlistview/azlistview.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_app/Screens/common/index.dart';

class ContactsPage extends StatefulWidget {
  @override
  _ContactsPageState createState() => _ContactsPageState();
}

class _ContactsPageState extends State<ContactsPage> {
  List<ContactInfo> contactList = List();
  List<ContactInfo> topList = List();

  @override
  void initState() {
    super.initState();
    // topList.add(ContactInfo(
    //     name: '新的朋友',
    //     tagIndex: '↑',
    //     // bgColor: Colors.orange,
    //     img: "http://placeimg.com/200/200/people",
    //     // iconData: Icons.person_add
    // ));
    // topList.add(ContactInfo(
    //     name: '群聊',
    //     tagIndex: '↑',
    //     bgColor: Colors.green,
    //     iconData: Icons.people));
    // topList.add(ContactInfo(
    //     name: '标签',
    //     tagIndex: '↑',
    //     bgColor: Colors.blue,
    //     iconData: Icons.local_offer));
    // topList.add(ContactInfo(
    //     name: '公众号',
    //     tagIndex: '↑',
    //     bgColor: Colors.blueAccent,
    //     iconData: Icons.person));
    loadData();
  }

  void loadData() async {
    //加载联系人列表
    rootBundle.loadString('assets/data/car_models.json').then((value) {
      List list = json.decode(value);
      list.forEach((v) {
        contactList.add(ContactInfo.fromJson(v));
      });
      _handleList(contactList);
    });
  }

  void _handleList(List<ContactInfo> list) {
    if (list == null || list.isEmpty) return;
    for (int i = 0, length = list.length; i < length; i++) {
      String pinyin = PinyinHelper.getPinyinE(list[i].name);
      String tag = pinyin.substring(0, 1).toUpperCase();
      list[i].namePinyin = pinyin;
      if (RegExp("[A-Z]").hasMatch(tag)) {
        list[i].tagIndex = tag;
      } else {
        list[i].tagIndex = "#";
      }
    }
    // A-Z sort.
    SuspensionUtil.sortListBySuspensionTag(contactList);

    // show sus tag.
    SuspensionUtil.setShowSuspensionStatus(contactList);

    // add topList.
    contactList.insertAll(0, topList);

    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: true,
        backgroundColor: Color(0xFFEDEDED),
        title: Text(
          'Contants',
          style: TextStyle(color: Color(0xFF171717)),
        ),
      ),
      body: AzListView(
        data: contactList,
        itemCount: contactList.length,
        itemBuilder: (BuildContext context, int index) {
          ContactInfo model = contactList[index];
          return Utils.getWeChatListItem(
            context,
            model,
            defHeaderBgColor: Color(0xFFE5E5E5),
          );
        },
        physics: BouncingScrollPhysics(),
        susItemBuilder: (BuildContext context, int index) {
          ContactInfo model = contactList[index];
          if ('↑' == model.getSuspensionTag()) {
            return Container();
          }
          return Utils.getSusItem(context, model.getSuspensionTag());
        },
        indexBarData: ['↑', '☆', ...kIndexBarData],
        indexBarOptions: IndexBarOptions(
          needRebuild: true,
          ignoreDragCancel: true,
          downTextStyle: TextStyle(fontSize: 12, color: Colors.white),
          downItemDecoration:
          BoxDecoration(shape: BoxShape.circle, color: Colors.green),
          indexHintWidth: 120 / 2,
          indexHintHeight: 100 / 2,
          indexHintDecoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage(Utils.getImgPath('ic_index_bar_bubble_gray')),
              fit: BoxFit.contain,
            ),
          ),
          indexHintAlignment: Alignment.centerRight,
          indexHintChildAlignment: Alignment(-0.25, 0.0),
          indexHintOffset: Offset(-20, 0),
        ),
      ),
    );
  }
}
`

**Comment by Sky24n** [comment]
Custom bean extends ISuspensionBean. add assets and network image parms.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by odejinmi** [comment]
I am just modifying the sample code and I want the contact part to be showing picture beside the name just as the picture sample

**Comment by Sky24n** [comment]
static Widget getWeChatItem(
BuildContext context,
ContactInfo model, {
Color defHeaderBgColor,
}) {
DecorationImage image;
//network image.
 if (model.img != null && model.img.isNotEmpty) {
 image = DecorationImage(
image: CachedNetworkImageProvider(model.img),
fit: BoxFit.contain,
);
 }else if(model.assetImg!=null && model.assetImg.isNotEmpty){
//aseet image.
image=xxx;
}
return ListTile(
leading: Container(
width: 36,
height: 36,
decoration: BoxDecoration(
shape: BoxShape.rectangle,
borderRadius: BorderRadius.circular(4.0),
color: model.bgColor ?? defHeaderBgColor,
image: image,
),
child: model.iconData == null
? null
: Icon(
model.iconData,
color: Colors.white,
size: 20,
),
),
title: Text(model.name),
onTap: () {
//LogUtil.e("onItemClick : $model");
Utils.showSnackBar(context, 'onItemClick : ${model.name}');
},
);
}


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by odejinmi** [comment]
thanks for your quick response it really work I appreciate it

**Comment by odejinmi** [comment]
please can I add search to the contact list? if yes how will I go about it

**Comment by Sky24n** [comment]
[search example](https://github.com/flutterchina/azlistview/blob/master/example/lib/ui/github_language_page.dart)
