### ISSUE TITLE
热门城市那一行怎么样让不一直在顶部悬浮的？

### ISSUE THREAD

**Issue by qcjxberin** [flutterchina/azlistview#36]
热门城市那一行怎么样让不一直在顶部悬浮的？

**Comment by Sky24n** [comment]
哪个示例？

**Comment by qcjxberin** [comment]
我自己参考着写的代码

**Comment by Sky24n** [comment]
没有看懂你的需求。。。

**Comment by qcjxberin** [comment]
![image](https://user-images.githubusercontent.com/5792218/98093614-1eda2180-1ec3-11eb-9583-04e6fe89d03e.png)
![image](https://user-images.githubusercontent.com/5792218/98093726-47fab200-1ec3-11eb-94c8-0ddf6b2d9288.png)

**Comment by qcjxberin** [comment]
我代码是这样写的，不知道为什么会出现下面这种情况
![image](https://user-images.githubusercontent.com/5792218/98093985-a031b400-1ec3-11eb-91e0-5f8c8bdc7b51.png)
那些A、B之类的被圈中的挡住了。

**Comment by Sky24n** [comment]
你tag写的固定值'★'。。。

**Comment by qcjxberin** [comment]
不能用固定值吗？

**Comment by qcjxberin** [comment]
如果不能的话，但我想实现最上面★热门国家和地区都显示应该怎么样弄的？

**Comment by Sky24n** [comment]
你好好看看demo里面是怎么写的，这种低级错误...

**Comment by Sky24n** [comment]
```dart
 susItemBuilder: (BuildContext context, int index) {
                          CityModel model = cityList[index];
                          String tag = model.getSuspensionTag();
                          return Utils.getSusItem(context, tag);//这里tag被你写成固定值，悬浮内容没变！
                        },
```

**Comment by qcjxberin** [comment]
懂了，谢谢！

**Comment by qcjxberin** [comment]
懂了，谢谢！
