### ISSUE TITLE
怎么样筛选数据并变更页面数据的？

### ISSUE THREAD

**Issue by qcjxberin** [flutterchina/azlistview#37]
![image](https://user-images.githubusercontent.com/5792218/98111791-1fcb7d00-1edc-11eb-8f3a-c5e02d9f48a6.png)
目前我的代码是这样写的，但是没有效果

**Comment by qcjxberin** [comment]
@Sky24n 能帮忙看一下吗？

**Comment by Sky24n** [comment]
[search example](https://github.com/flutterchina/azlistview/blob/master/example/lib/ui/github_language_page.dart)

**Comment by qcjxberin** [comment]
Ok thanks, let me see
