### ISSUE TITLE
当最后的一组高度的整体不能撑满屏幕时,滑动到最后一组,再定位到其他组有问题

### ISSUE THREAD

**Issue by dinoandcat** [flutterchina/azlistview#38]
当最后的一组高度的整体不能撑满屏幕时, 滑动到最后一组, 再定位到其索引时,定位有问题. 不能滚动到相应索引的第一列.

**Comment by Sky24n** [comment]
是这样的，它们是相互联动的，定位最后一个引起回弹导致定位到当前列表真实tag。

**Comment by dinoandcat** [comment]
比如我滚动到z后, 由于z组的整体高度不够整个屏幕,然后我再选择其他的组比如中间的L组,这时滚动到L组时,没有滚动到L组的第一列.

**Comment by Sky24n** [comment]
发代码吧

**Comment by Sky24n** [comment]
fix, 版本v1.1.0

**Comment by dinoandcat** [comment]
超级速度,谢谢

**Comment by dinoandcat** [comment]
测试了一下,还是有问题.
![](http://blog.golang.chat/biubiugame004.gif)

**Comment by Sky24n** [comment]
描述详细点

**Comment by Sky24n** [comment]
我这边没有这个问题，请尝试真机测试

**Comment by dinoandcat** [comment]
测试了真机没有问题,谢谢.
