### ISSUE TITLE
Overflow for indexBar

### ISSUE THREAD

**Issue by qbait** [flutterchina/azlistview#39]
I'm getting an overflow error when the keyboard is shown. What's the best way to avoid it?

<img width="345" alt="Screenshot 2020-12-08 at 22 53 00" src="https://user-images.githubusercontent.com/2264901/101545879-3451d800-39a8-11eb-855b-20bacf80655c.png">

**Comment by Sky24n** [comment]
```dart
Scaffold(
      resizeToAvoidBottomInset: false,
)
```

**Comment by qbait** [comment]
Is there another way, I would like my Scaffold's body to be resized. 
Currently, there is also overflow in the landscape mode, I thought there is a way to get rid of it too?

**Comment by Sky24n** [comment]
Because the indexbar is a fixed height. So it will overflow in landscape  mode.

**Comment by qbait** [comment]
Is there any way to avoid it? Shall I wrap it in a specific widget? Or can I hide indexbar programmatically?

**Comment by Sky24n** [comment]
In landscape mode , you can set indexBarData = [] .

**Comment by qbait** [comment]
Actually is there a way to programmatically discover if indexBar overflows and then set `indexBarData = [] `.
I can think of 3 scenarios right now (landscape, keyboard visible, small screen).
Would be nice if we can detect somehow in `AzListView` that indexBar overflows instead of checking all the conditions.

**Comment by qbait** [comment]
I fixed that by wrapping `AzListView` in `LayoutBuilder` like
```
child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          return AzListView(
            data: presentations,
            itemCount: presentations.length,
            itemBuilder: (BuildContext context, int index) {
              final presentation = presentations[index];
              return _tile(presentation);
            },
            indexBarData: constraints.maxHeight > 400 ? SuspensionUtil.getTagIndexList(presentations) : [],
          );
        },
      )
```

Not a big fan of hardcoded `constraints.maxHeight > 400` but don't have a better idea to solve it right now.
