### ISSUE TITLE
作者你好，我有个小问题想咨询一下，不知道这个问题算不算bug

### ISSUE THREAD

**Issue by lanjiachuan** [flutterchina/azlistview#4]
首先感谢你提供的组件，我在使用组件时发现了一个小问题，我不知道是不是该定义为bug。 当我把模拟数据加载完 通过右侧的字母列表 滑动选中对应的区域 屏幕中间会显示当前停留的字母区域的 灰色的字母，这个滑动的时候 都是ok的，但是发现如果用手直接点对应的字母后  该字母不会消失，点击屏幕周边 也不会消失，如果重新用手在字母列表上滑动一下 则能消失。 不知是否是bug 还是我缺少了什么设置。希望能得到你的帮助

**Comment by Sky24n** [comment]
请问是v0.1.1版本吗

**Comment by lanjiachuan** [comment]
我现在用的是v0.1.0

**Comment by Sky24n** [comment]
v0.1.1最新版已修复

**Comment by lanjiachuan** [comment]
更新过了，可以了 没有这个问题了 谢谢帮助
