### ISSUE TITLE
悬浮的a-z会重复

### ISSUE THREAD

**Issue by miaozhang9** [flutterchina/azlistview#40]
悬浮的a-z会重复
<img width="360" alt="WX20201209-103641@2x" src="https://user-images.githubusercontent.com/8730843/101566747-7ad81e80-3a0a-11eb-9cb6-9ec8b76ade51.png">

**Comment by Sky24n** [comment]
## Changelog

Please see the [Changelog](https://github.com/flutterchina/azlistview/blob/master/CHANGELOG.md) page to know what's recently changed.  
v1.1.0  
itemBuilder不要包含Header，因为它是在内部自动合并的。

**Comment by miaozhang9** [comment]
谢谢，刚看了代码，确实有两个地方添加，把itemBuilder里边的注释了。
