### ISSUE TITLE
请问是否支持点击状态栏回到顶部

### ISSUE THREAD

**Issue by wenxiangjiang** [flutterchina/azlistview#41]
如题，谢谢。

**Comment by Sky24n** [comment]
自己悟吧！

**Comment by wenxiangjiang** [comment]
没有悟出来，默认情况下在真机上没生效😄

**Comment by Sky24n** [comment]
那就先去学基础...

**Comment by wenxiangjiang** [comment]
额...

**Comment by Sky24n** [comment]
需要什么功能自己写就是，flutter不是iOS！

**Comment by wenxiangjiang** [comment]
额，我不知道 flutterchina 的人为什么要用这样的口气回复用户。

flutter 确实不是 iOS，但是不论是 ListView / GridView 还是直接继承自 StatefulWidget 的 ReorderableListView 在 iOS 平台下也都是支持点击状态栏回到顶部功能的，flutter 一样也会照顾到不同平台的特有特性。

我在项目中使用到了 azlistview，我觉得写的很棒，但是在真机上测试发现点击状态栏没有回到顶部，因为才来咨询一下。

**Comment by Sky24n** [comment]
因为很生气，readme也不看源码也不看！基于[scrollable_positioned_list](https://pub.flutter-io.cn/packages/scrollable_positioned_list).

**Comment by likeSo** [comment]
@Sky24n 我寻思你readme也没写功能介绍吧？另外你为什么那么自信所有人都用过你提到的这个依赖？如果你的readme写的清楚的话，我也不至于想从issue里面找使用介绍了。。。

**Comment by likeSo** [comment]
@Sky24n 你说到源码，好像源码里面也没写什么注释的样子。。。
```dart
/// AzListView
class AzListView extends StatefulWidget {
  AzListView({
    Key key,
    @required this.data,
    @required this.itemCount,
    @required this.itemBuilder,
    this.itemScrollController,
    this.itemPositionsListener,
    this.physics,
    this.padding,
    this.susItemBuilder,
    this.susItemHeight = kSusItemHeight,
    this.susPosition,
    this.indexHintBuilder,
    this.indexBarData = kIndexBarData,
    this.indexBarWidth = kIndexBarWidth,
    this.indexBarHeight,
    this.indexBarItemHeight = kIndexBarItemHeight,
    this.indexBarAlignment = Alignment.centerRight,
    this.indexBarMargin,
    this.indexBarOptions = const IndexBarOptions(),
  }) : super(key: key);
```

**Comment by Sky24n** [comment]
> 
> 
> @Sky24n 我寻思你readme也没写功能介绍吧？另外你为什么那么自信所有人都用过你提到的这个依赖？如果你的readme写的清楚的话，我也不至于想从issue里面找使用介绍了。。。

关于点击状态栏回到顶部这个问题？
你们使用的官方滚动都是由系统提供的，我这边是基于google提供的三方库scrollable_positioned_list二次封装的，支不支持这个功能跟本库有关联吗？
![微信图片_20210702100147](https://user-images.githubusercontent.com/15412262/124209918-1226cf80-db1d-11eb-82de-83dfbf4d575f.png)

**Comment by Sky24n** [comment]
> 
> 
> @Sky24n 你说到源码，好像源码里面也没写什么注释的样子。。。
> 
> ```dart
> /// AzListView
> class AzListView extends StatefulWidget {
>   AzListView({
>     Key key,
>     @required this.data,
>     @required this.itemCount,
>     @required this.itemBuilder,
>     this.itemScrollController,
>     this.itemPositionsListener,
>     this.physics,
>     this.padding,
>     this.susItemBuilder,
>     this.susItemHeight = kSusItemHeight,
>     this.susPosition,
>     this.indexHintBuilder,
>     this.indexBarData = kIndexBarData,
>     this.indexBarWidth = kIndexBarWidth,
>     this.indexBarHeight,
>     this.indexBarItemHeight = kIndexBarItemHeight,
>     this.indexBarAlignment = Alignment.centerRight,
>     this.indexBarMargin,
>     this.indexBarOptions = const IndexBarOptions(),
>   }) : super(key: key);
> ```

有认真看吗？还要我怎么写注释？
![微信图片_20210702100649](https://user-images.githubusercontent.com/15412262/124210038-4dc19980-db1d-11eb-87c7-0c9630072378.png)

**Comment by likeSo** [comment]
> > @Sky24n 我寻思你readme也没写功能介绍吧？另外你为什么那么自信所有人都用过你提到的这个依赖？如果你的readme写的清楚的话，我也不至于想从issue里面找使用介绍了。。。
> 
> 关于点击状态栏回到顶部这个问题？
> 你们使用的官方滚动都是由系统提供的，我这边是基于google提供的三方库scrollable_positioned_list二次封装的，支不支持这个功能跟本库有关联吗？
> ![微信图片_20210702100147](https://user-images.githubusercontent.com/15412262/124209918-1226cf80-db1d-11eb-82de-83dfbf4d575f.png)

我说的是关于你的这个框架如何使用的问题，我看了几遍readme没看出来怎么实现你贴的图片的功能。所以才来issue里面尝试找到一些使用的案例

**Comment by likeSo** [comment]
> > @Sky24n 你说到源码，好像源码里面也没写什么注释的样子。。。
> > ```dart
> > /// AzListView
> > class AzListView extends StatefulWidget {
> >   AzListView({
> >     Key key,
> >     @required this.data,
> >     @required this.itemCount,
> >     @required this.itemBuilder,
> >     this.itemScrollController,
> >     this.itemPositionsListener,
> >     this.physics,
> >     this.padding,
> >     this.susItemBuilder,
> >     this.susItemHeight = kSusItemHeight,
> >     this.susPosition,
> >     this.indexHintBuilder,
> >     this.indexBarData = kIndexBarData,
> >     this.indexBarWidth = kIndexBarWidth,
> >     this.indexBarHeight,
> >     this.indexBarItemHeight = kIndexBarItemHeight,
> >     this.indexBarAlignment = Alignment.centerRight,
> >     this.indexBarMargin,
> >     this.indexBarOptions = const IndexBarOptions(),
> >   }) : super(key: key);
> > ```
> 
> 有认真看吗？还要我怎么写注释？
> ![微信图片_20210702100649](https://user-images.githubusercontent.com/15412262/124210038-4dc19980-db1d-11eb-87c7-0c9630072378.png)

你可能误会了“看懂”这个词，能看懂你的注释和能看懂你的框架如何使用貌似是两码事。。比如data那个的注释“with XXX data”，请问我们应该能从这句注释里面读懂什么呢？能看出来data是干嘛用的吗？如果不能的话，这句注释和废话有什么区别吗...

**Comment by Sky24n** [comment]
> 
> 
> > > @Sky24n 我寻思你readme也没写功能介绍吧？另外你为什么那么自信所有人都用过你提到的这个依赖？如果你的readme写的清楚的话，我也不至于想从issue里面找使用介绍了。。。
> > 
> > 
> > 关于点击状态栏回到顶部这个问题？
> > 你们使用的官方滚动都是由系统提供的，我这边是基于google提供的三方库scrollable_positioned_list二次封装的，支不支持这个功能跟本库有关联吗？
> > ![微信图片_20210702100147](https://user-images.githubusercontent.com/15412262/124209918-1226cf80-db1d-11eb-82de-83dfbf4d575f.png)
> 
> 我说的是关于你的这个框架如何使用的问题，我看了几遍readme没看出来怎么实现你贴的图片的功能。所以才来issue里面尝试找到一些使用的案例


这里不都是例子吗？
![微信图片_20210702104005](https://user-images.githubusercontent.com/15412262/124212659-efe38080-db21-11eb-89c9-5d0c9a49c04e.png)

**Comment by Sky24n** [comment]
> 
> 
> > > @Sky24n 你说到源码，好像源码里面也没写什么注释的样子。。。
> > > ```dart
> > > /// AzListView
> > > class AzListView extends StatefulWidget {
> > >   AzListView({
> > >     Key key,
> > >     @required this.data,
> > >     @required this.itemCount,
> > >     @required this.itemBuilder,
> > >     this.itemScrollController,
> > >     this.itemPositionsListener,
> > >     this.physics,
> > >     this.padding,
> > >     this.susItemBuilder,
> > >     this.susItemHeight = kSusItemHeight,
> > >     this.susPosition,
> > >     this.indexHintBuilder,
> > >     this.indexBarData = kIndexBarData,
> > >     this.indexBarWidth = kIndexBarWidth,
> > >     this.indexBarHeight,
> > >     this.indexBarItemHeight = kIndexBarItemHeight,
> > >     this.indexBarAlignment = Alignment.centerRight,
> > >     this.indexBarMargin,
> > >     this.indexBarOptions = const IndexBarOptions(),
> > >   }) : super(key: key);
> > > ```
> > 
> > 
> > 有认真看吗？还要我怎么写注释？
> > ![微信图片_20210702100649](https://user-images.githubusercontent.com/15412262/124210038-4dc19980-db1d-11eb-87c7-0c9630072378.png)
> 
> 你可能误会了“看懂”这个词，能看懂你的注释和能看懂你的框架如何使用貌似是两码事。。比如data那个的注释“with XXX data”，请问我们应该能从这句注释里面读懂什么呢？能看出来data是干嘛用的吗？如果不能的话，这句注释和废话有什么区别吗...

别人为什么能用？

**Comment by likeSo** [comment]
> > > > @Sky24n 你说到源码，好像源码里面也没写什么注释的样子。。。
> > > > ```dart
> > > > /// AzListView
> > > > class AzListView extends StatefulWidget {
> > > >   AzListView({
> > > >     Key key,
> > > >     @required this.data,
> > > >     @required this.itemCount,
> > > >     @required this.itemBuilder,
> > > >     this.itemScrollController,
> > > >     this.itemPositionsListener,
> > > >     this.physics,
> > > >     this.padding,
> > > >     this.susItemBuilder,
> > > >     this.susItemHeight = kSusItemHeight,
> > > >     this.susPosition,
> > > >     this.indexHintBuilder,
> > > >     this.indexBarData = kIndexBarData,
> > > >     this.indexBarWidth = kIndexBarWidth,
> > > >     this.indexBarHeight,
> > > >     this.indexBarItemHeight = kIndexBarItemHeight,
> > > >     this.indexBarAlignment = Alignment.centerRight,
> > > >     this.indexBarMargin,
> > > >     this.indexBarOptions = const IndexBarOptions(),
> > > >   }) : super(key: key);
> > > > ```
> > > 
> > > 
> > > 有认真看吗？还要我怎么写注释？
> > > ![微信图片_20210702100649](https://user-images.githubusercontent.com/15412262/124210038-4dc19980-db1d-11eb-87c7-0c9630072378.png)
> > 
> > 
> > 你可能误会了“看懂”这个词，能看懂你的注释和能看懂你的框架如何使用貌似是两码事。。比如data那个的注释“with XXX data”，请问我们应该能从这句注释里面读懂什么呢？能看出来data是干嘛用的吗？如果不能的话，这句注释和废话有什么区别吗...
> 
> 别人为什么能用？难道还要手把手教学？

为什么就是不能承认自己readme和注释什么都没写呢？你的readme里面确实只有Installation没有Usage啊，有人来问你怎么使用不是很正常么？别人来问你你说别人不看注释，其实注释也啥都没写啊...确实，别人都能用就我们不能用，打扰了

**Comment by Sky24n** [comment]
> 
> 
> > > > > @Sky24n 你说到源码，好像源码里面也没写什么注释的样子。。。
> > > > > ```dart
> > > > > /// AzListView
> > > > > class AzListView extends StatefulWidget {
> > > > >   AzListView({
> > > > >     Key key,
> > > > >     @required this.data,
> > > > >     @required this.itemCount,
> > > > >     @required this.itemBuilder,
> > > > >     this.itemScrollController,
> > > > >     this.itemPositionsListener,
> > > > >     this.physics,
> > > > >     this.padding,
> > > > >     this.susItemBuilder,
> > > > >     this.susItemHeight = kSusItemHeight,
> > > > >     this.susPosition,
> > > > >     this.indexHintBuilder,
> > > > >     this.indexBarData = kIndexBarData,
> > > > >     this.indexBarWidth = kIndexBarWidth,
> > > > >     this.indexBarHeight,
> > > > >     this.indexBarItemHeight = kIndexBarItemHeight,
> > > > >     this.indexBarAlignment = Alignment.centerRight,
> > > > >     this.indexBarMargin,
> > > > >     this.indexBarOptions = const IndexBarOptions(),
> > > > >   }) : super(key: key);
> > > > > ```
> > > > 
> > > > 
> > > > 有认真看吗？还要我怎么写注释？
> > > > ![微信图片_20210702100649](https://user-images.githubusercontent.com/15412262/124210038-4dc19980-db1d-11eb-87c7-0c9630072378.png)
> > > 
> > > 
> > > 你可能误会了“看懂”这个词，能看懂你的注释和能看懂你的框架如何使用貌似是两码事。。比如data那个的注释“with XXX data”，请问我们应该能从这句注释里面读懂什么呢？能看出来data是干嘛用的吗？如果不能的话，这句注释和废话有什么区别吗...
> > 
> > 
> > 别人为什么能用？难道还要手把手教学？
> 
> 为什么就是不能承认自己readme和注释什么都没写呢？你的readme里面确实只有Installation没有Usage啊，有人来问你怎么使用不是很正常么？别人来问你你说别人不看注释，其实注释也啥都没写啊...确实，别人都能用就我们不能用，打扰了

使用在example都有，为什么一定要写在readme里面，自己不去运行下项目还要怪别人

**Comment by likeSo** [comment]
> > > > > > @Sky24n 你说到源码，好像源码里面也没写什么注释的样子。。。
> > > > > > ```dart
> > > > > > /// AzListView
> > > > > > class AzListView extends StatefulWidget {
> > > > > >   AzListView({
> > > > > >     Key key,
> > > > > >     @required this.data,
> > > > > >     @required this.itemCount,
> > > > > >     @required this.itemBuilder,
> > > > > >     this.itemScrollController,
> > > > > >     this.itemPositionsListener,
> > > > > >     this.physics,
> > > > > >     this.padding,
> > > > > >     this.susItemBuilder,
> > > > > >     this.susItemHeight = kSusItemHeight,
> > > > > >     this.susPosition,
> > > > > >     this.indexHintBuilder,
> > > > > >     this.indexBarData = kIndexBarData,
> > > > > >     this.indexBarWidth = kIndexBarWidth,
> > > > > >     this.indexBarHeight,
> > > > > >     this.indexBarItemHeight = kIndexBarItemHeight,
> > > > > >     this.indexBarAlignment = Alignment.centerRight,
> > > > > >     this.indexBarMargin,
> > > > > >     this.indexBarOptions = const IndexBarOptions(),
> > > > > >   }) : super(key: key);
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 有认真看吗？还要我怎么写注释？
> > > > > ![微信图片_20210702100649](https://user-images.githubusercontent.com/15412262/124210038-4dc19980-db1d-11eb-87c7-0c9630072378.png)
> > > > 
> > > > 
> > > > 你可能误会了“看懂”这个词，能看懂你的注释和能看懂你的框架如何使用貌似是两码事。。比如data那个的注释“with XXX data”，请问我们应该能从这句注释里面读懂什么呢？能看出来data是干嘛用的吗？如果不能的话，这句注释和废话有什么区别吗...
> > > 
> > > 
> > > 别人为什么能用？难道还要手把手教学？
> > 
> > 
> > 为什么就是不能承认自己readme和注释什么都没写呢？你的readme里面确实只有Installation没有Usage啊，有人来问你怎么使用不是很正常么？别人来问你你说别人不看注释，其实注释也啥都没写啊...确实，别人都能用就我们不能用，打扰了
> 
> 使用在example都有，为什么一定要写在readme里面，自己不去运行下项目，还说找不到案例，还要怪别人

没找到example是俺的错。可是项目用框架不都是看文档使用么，为什么不给文档让用户自己测，你提供了案例，但是你的案例有说明每个字段负责干什么吗？注释注释也没有，人家问你怎么用你也一句话掰成半句说。总之你是作者你有理，打扰了

**Comment by xiaochenghua** [comment]
吵架还挺好看的～
