### ISSUE TITLE
在快速滑动后，内存暴涨，导致崩溃

### ISSUE THREAD

**Issue by 9527001** [flutterchina/azlistview#49]

**Comment by 9527001** [comment]
是flutter的图片内存问题，暂时解决了

**Comment by ansonhorse** [comment]
> 是flutter的图片内存问题，暂时解决了

可以的话，希望能尽量说一下`原因`和`解决方法`，谢谢

**Comment by 9527001** [comment]
flutter 在ios上运行 图片使用内存加载基本不释放。
flutter在ios上的图片缓存一直有问题。现在采用压缩的方法解决，压缩到1M以内。采用外接纹理的方法，可以永久解决，目前没有发现开源的解决方案
