### ISSUE TITLE
发现有个bug

### ISSUE THREAD

**Issue by summerNa** [flutterchina/azlistview#6]
Scaffold(
        appBar: new AppBar(
          title: new Text(widget.title),
          centerTitle: true,
        ),
        body: new Column(
          children: <Widget>[
            Container(
              alignment: Alignment.centerLeft,
              padding: const EdgeInsets.only(left: 15.0),
              height: 50.0,
              child: Text("当前城市: 成都市"),
            ),
            Expanded(
                flex: 1,
                child: new AzListView(
                  data: _cityList,
                  topData: _hotCityList,
                  itemBuilder: (context, model) => _buildListItem(model),
                  suspensionWidget: _buildSusWidget(_suspensionTag),
                  isUseRealIndex: true,
                  itemHeight: _itemHeight,
                  suspensionHeight: _suspensionHeight,
                  onSusTagChanged: _onSusTagChanged,
                ))
          ],
        ));我发现这个必须要放在Scaffold里面并且要有appbar，不然点击侧边索引后对应的索引标题会有部分重复啊，不知道是我写错了还是有问题，麻烦作者确认一下

**Comment by Sky24n** [comment]
肯定是你哪里写错了，仔细查看示例，有可能是没有排序 SuspensionUtil.sortListBySuspensionTag(list);

**Comment by summerNa** [comment]
写了呀，相同的代码，引入到不同的文件里面，一个是appbar的，正常显示，一个不是appbar的，就有点重复。。。。

**Comment by Sky24n** [comment]
全部代码贴出来，我试下。
我这个项目里面就没有用Scaffold，[select_city_page](https://github.com/Sky24n/GreenTravel/blob/master/green_travel_a/lib/ui/pages/select_city_page.dart)

**Comment by summerNa** [comment]
我在您的demo flutter_wanandroid里面的city_select_page试了一下，也是这样，我是模拟器跑的。。。。
