### ISSUE TITLE
有重复的A-Z标签

### ISSUE THREAD

**Issue by jonasli** [flutterchina/azlistview#68]
请教一下我的列表里面每个字符都被重复了2次，这是为什么呢？
<img width="318" alt="Screen Shot 2021-10-12 at 3 25 07 PM" src="https://user-images.githubusercontent.com/9443954/136917733-71666e69-cfef-44b7-8cc0-32770f851058.png">

主要的几段代码，我也没看出来有什么问题。
 `
class _CitySelectListPageState extends State<CitySelectListPage> {
  List<CityModel> _cityList = List.empty();
  List<CityModel> _hotCityList = [];
  double? _suspensionHeight = 40;
  double? _itemHeight = 50;
  final TextStyle hotCityStyle =
      TextStyle(fontSize: 14, color: Colors.grey.shade600);

  @override
  void initState() {
    super.initState();
    _hotCityList.add(CityModel(name: '北京市', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '广州市', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '成都市', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '深圳市', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '杭州市', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '武汉市', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '上海', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '南京', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '合肥', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '苏州', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '无锡', tagIndex: '★'));
    _hotCityList.add(CityModel(name: '天津', tagIndex: '★'));
    SuspensionUtil.setShowSuspensionStatus(_cityList);
    Future.delayed(Duration(milliseconds: 500), () {
      _loadData();
    });
  }

  void _loadData() async {
    //加载城市列表
    rootBundle
        .loadString(Constant.ASSETS_METADATA + 'china_city_list.json')
        .then((value) {
      Map provinceMap = json.decode(value);

      provinceMap.forEach((key, item) {
//        print('name: ${item['name']}');
        Map cityMap = item["c"];
        cityMap.forEach((key, item) {
          _cityList = [..._cityList, CityModel(name: item['n'], code: key)];
        });
      });
      _handleList(_cityList);
      setState(() {});
    });
  }

  void _handleList(List<CityModel> list) {
//    if (list == null || list.isEmpty) return;
    for (int i = 0, length = list.length; i < length; i++) {
      String pinyin = PinyinHelper.getPinyinE(list[i].name);
      String tag = pinyin.substring(0, 1).toUpperCase();
      list[i].namePinyin = pinyin;
      if (RegExp("[A-Z]").hasMatch(tag)) {
        list[i].tagIndex = tag;
      } else {
        list[i].tagIndex = "#";
      }
    }
    //根据A-Z排序
    SuspensionUtil.sortListBySuspensionTag(_cityList);

    // show sus tag.
    SuspensionUtil.setShowSuspensionStatus(_cityList);

    // add header.
    _cityList.insert(0, CityModel(name: 'header', tagIndex: '★'));

    setState(() {});
  }`

**Comment by farhanfr** [comment]
hi, how you solving?
