### ISSUE TITLE
大佬，有个问题

### ISSUE THREAD

**Issue by eric112** [flutterchina/azlistview#7]
当页面数据撑不满一屏时，失去了拖动回弹的效果

**Comment by Sky24n** [comment]
listview本身未满一屏是没有回弹

**Comment by eric112** [comment]
listview在不满一屏时，不添加controller的时候，默认是有回弹的，加了controller之后才没有这个效果，不过可以设置physics来使他拥有的

**Comment by eric112** [comment]
是否可以添加接收一个physics，让我们可以自己设置？

**Comment by Sky24n** [comment]
后续会把能开放的都开放出来

**Comment by Sky24n** [comment]
> 是否可以添加接收一个physics，让我们可以自己设置？

v0.1.2已开放physics。

**Comment by eric112** [comment]
> > 是否可以添加接收一个physics，让我们可以自己设置？
> 
> v0.1.2已开放physics。

可以了，多谢大佬🙏
