### ISSUE TITLE
发现一个关于分组后排序的问题。

### ISSUE THREAD

**Issue by oh-jy** [flutterchina/azlistview#9]
在相同的字母分组下 比如都是Z 然后名字叫 张**  周**，这样同一组内会乱序 并没有按照张姓结束后才是周姓这样子排序

**Comment by Sky24n** [comment]
库提供的是根据首字母排序的，肯定会乱，你得直接写排序。

**Comment by oh-jy** [comment]
直接排序就无法实现分组，直接按照首字排序了。无法先分组再排序


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Sky24n** [comment]
先按a-z排序，再把每一类分别排序就可以了
